app/main/models.py
import datetime as dt
from app.extensions import db



class Todo(db.Model):
	__tablename__ = 'todos'
	id = db.Column(db.Integer, autoincrement=True, primary_key=True)
	title = db.Column(db.String(20), nullable=False)
	description = db.Column(db.String(200), nullable=True)
	completed = db.Column(db.Boolean(), default=False)
	delayed = db.Column(db.Boolean(), default=False)
	created_at = db.Column(db.DateTime, nullable=False, default=dt.datetime.now)
	date_at = db.Column(db.DateTime, nullable=True)
	user_id = db.Column(db.Integer, db.ForeignKey('users.id'))  
	
	@property
	def serialize(self):
		return{
			'id':self.id,
			'title':self.title,
			'description':self.description,
			'completed': self.completed,
			'delayed':self.delayed,
			'date_at':self.date_at,
			'user_id':self.user_id
		}

	def __init__(self, title, description , date_at, user_id):
		self.title = title
		self.description = description
		self.user_id= user_id

	def __repr__(self):  
		return f"<Todo {'%s','%s'}>" % (self.id, self.user_id)

app/main/forms.py
import datetime as dt
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField, PasswordField, BooleanField, DateTimeField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Length, Email

from .models import Todo

class addForm(FlaskForm):
    title = StringField('Title', validators=[ DataRequired("Title is required"), Length(max=64) ] )
    description = StringField('Message', validators=[ DataRequired("Message is required"), Length(max=200) ] )
    date_at = DateTimeField("Date", default=dt.datetime.now, validators=[DataRequired()])

app/main/__init__.py
from . import views

app/main/views.py
import os
import json

from flask import Blueprint
from flask import render_template, redirect, url_for
from flask import send_file, send_from_directory
from flask import Response, json

from flask import request
from flask_restful import Resource

from flask_login import login_required
from flask_login import current_user

from .forms import addForm
from .models import Todo
from app.extensions import db, api
from app.settings import CLIENT_IMAGES

from flask.views import MethodView


class TodoView(MethodView):
 
    def get(self, id=None, page=1):
        if not id:
            products = Product.query.paginate(page, 10).items
            res = {}
            for product in products:
                res[product.id] = {
                    'name': product.name,
                    'price': str(product.price),
                }
        else:
            product = Product.query.filter_by(id=id).first()
            if not product:
                abort(404)
            res = {
                'name': product.name,
                'price': str(product.price),
            }
        return jsonify(res)
 
    def post(self):
        name = request.form.get('name')
        price = request.form.get('price')
        product = Product(name, price)
        db.session.add(product)
        db.session.commit()
        return jsonify({product.id: {
            'name': product.name,
            'price': str(product.price),
        }})
 
    def put(self, id):
        # Update the record for the provided id
        # with the details provided.
        return
 
    def delete(self, id):
        # Delete the record for the provided id.
        return




blueprint = Blueprint('main', __name__, template_folder='templates', url_prefix='/main', static_folder='static',static_url_path='/static/')


@blueprint.route("/get-image/<image>",methods=["GET"])
@login_required
def getImage(image):
    try:
        return send_from_directory(CLIENT_IMAGES, filename=image, mimetype='image/jpg', as_attachment=True) #attachment_filename='avatar.jpg',
    except FileNotFoundError:
        return abort(404)


@blueprint.route('/')
@login_required
def index():

    form = addForm()
    if form.validate_on_submit():
        todo = Todo(
            form.title.data,
            form.description.data,
            form.date_at.data,
            current_user.id
        )
        db.session.add(todo)
        db.session.commit()
        resp = Response( json.dumps({"status":"success","msg":"save successfull",})  , status=200, mimetype='application/json' )
        return resp

    avatar = True if os.path.exists(os.path.join(CLIENT_IMAGES, '{}.jpg'.format(current_user.id))) else False
    todos = Todo.query.filter_by(user_id=current_user.id).all()
    return render_template('main.html', todos=todos, user=current_user, form=form, avatar = avatar, title="Tasks to do")


@blueprint.route('/add', methods=["GET", "POST"])
@login_required
def addTodo():

    form = addForm()
    if form.validate_on_submit():
        todo = Todo(
            form.title.data,
            form.description.data,
            form.date_at.data,
            current_user.id
        )
        db.session.add(todo)
        db.session.commit()
        resp = Response( json.dumps({"status":"success","msg":"saved successfull",})  , status=200, mimetype='application/json' )
        return resp
    resp = Response( json.dumps({"status":"error","msg":"Error",})  , status=200, mimetype='application/json' )
    return resp


@blueprint.route('/delete/<int:id>')
@login_required
def delTodo(id):
    
    task = Todo.query.filter_by(tasks=current_user,id=id).first()
    if task is None:
        resp = Response( json.dumps({"status":"error","msg":"dont allowed"})  , status=200, mimetype='application/json' )
        return resp
    else:
        db.session.delete(task)
        db.session.commit()
        resp = Response( json.dumps({"status":"success","msg":"deleted successfull",'remove':True,"id":id})  , status=200, mimetype='application/json' )
        return resp



class StickyNotes(Resource):

    def get(self, id=None, page=1):
        if not id:
            todos = Todo.query.filter_by(tasks=current_user).paginate(page, 10).items
            res = {}
            for todo in todos:
                res[todo.id] = {
                    'title': todo.title,
                    'description': todo.description,
                    'date_at': str(todo.date_at),
                }
        else:
            todo = Todo.query.filter_by(id=id).first()
            if not todo:
                abort(404)
            res = {
                'title': todo.title,
                'description': todo.description,
                'date_at': str(todo.date_at),
            }
        return jsonify(res)

 
    def post(self):
        name = request.form.get('name')
        price = request.form.get('price')
        product = Product(name, price)
        db.session.add(product)
        db.session.commit()
        return jsonify({product.id: {
            'name': product.name,
            'price': str(product.price),
        }})
 
    def put(self, id):
        # Update the record for the provided id
        # with the details provided.
        return
 
    def delete(self, id):

        json_data = request.get_json(force=True)
        if not json_data:
               return {'message': 'No input data provided'}, 400

        # Delete the record for the provided id.
        return

api.add_resource(StickyNotes, '/api/v1/', endpoint='main')
api.add_resource(StickyNotes, '/api/v1/<int:id>', endpoint='main')

app/main/templates/components/todos.html
{% macro todos_list(todos) %}

	{% for todo in todos %}
		{% set status='bg-success' %}
		{% set dias = todo.created_at|countdays %}
		{% set status=(status,'bg-warning')[dias>7]%}
		{% set status=(status,'bg-danger')[dias>30]%}
		{% set status=(status,'bg-secondary')[todo.completed]%}
		<div class="col mt-3 " id="todo-{{todo.id}}">
			<div class="card text-white {{status}} mb-3 center-block" style="max-width: 18rem; height: 250px;">
				<div class="card-header">
					<a class="submit text-light ml-2" href="{{url_for('main.delTodo', id=todo.id, _external=True)}}" style="font-size: 0.5rem;"><i class="far fa-3x fa-trash-alt" aria-hidden="true"></i></a>
					<a class="submit text-light ml-2" href="#" style="font-size: 0.5rem;"><i class="far fa-3x fa-calendar-check"></i></a>
					<a class="submit text-light ml-2" href="#" style="font-size: 0.5rem;"><i class="far fa-3x fa-calendar"></i></a>
				</div>
				<div class="card-body">
					<h5 class="card-title">{{ todo.title }}</h5>
					<p class="card-text">{{ todo.description }}</p>
				</div>	
			</div>
		</div>
	{% endfor %}

{% endmacro %}

app/main/templates/main.html
{% extends 'base.html' %}

{% block title %}Flask Example{% endblock %}

{% block head %}

    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/lib/toastr.min.css') }}"  media="screen"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/lib/bootstrap-datetimepicker.min.css') }}"  media="screen"/>
    <link rel="stylesheet" href="{{ url_for('main.static', filename='css/styles.css') }}"  media="screen"/>

    <style type="text/css">
        body{
            background-color:#F9FAFC !important;
        }
    </style>
{% endblock %}



{% block content %}
<div class="wrapper">



        <!-- Sidebar -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <a href="#" class="img logo rounded-circle mb-5" style="background-image: url({{ url_for('main.getImage',image='{}.jpg'.format(current_user.id)) }});"></a>
                <!-- <h3>Helizonaldo Morais</h3> -->
            </div>
    
            <ul class="list-unstyled components">
                <p>{{user.username}}</p>
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-user-cog"></i> Administrator</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="#"><i class="far fa-user"></i> Users</a>
                        </li>
                    </ul>
                </li>
    
                <li>
                    <a href="#"><i class="fas fa-key"></i> Password</a>
                </li>
                <li>
                    <a href="{{ url_for('auth.logout')}}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                </li>
            </ul>        
        </nav>

        <div id="content" class="container-fluid h-100 px-0">


            <nav class="mb-1 navbar navbar-expand-lg navbar-dark  bg-primary">
      
                <a href="#" class="navbar-brand">
                    <img src="{{ url_for('static', filename='images/icon.svg') }}" width="25" alt="" class="d-inline-block align-middle mr-2">
                    <span class="font-weight-bold">Sticky Notes</span>
                </a>    
                
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                    
                        <li class="nav-item active">
                            <a class="nav-link btn btn-info" data-toggle="modal" data-target="#exampleModal">
                                <i class="far fa-file"></i> New
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>    
            
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle pointer ml-2" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-sort-amount-down"></i> Order by
                            </a>
                            <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#"><i class="fas fa-hourglass-end"></i> Very late</a>
                                <a class="dropdown-item" href="#"><i class="fas fa-hourglass-half"></i> Late</a>
                                <a class="dropdown-item" href="#"><i class="far fa-calendar-check"></i> Done</a>
                            </div>
                        </li>
                    </ul>
                  
                    <ul class="navbar-nav ml-auto nav-flex-icons">
                        
                        <li class="nav-item active ml-2">
                            <a id="countTodo" class="nav-link waves-effect waves-light active"> {{ todos|length }} 
                                <i class="fas fa-envelope"></i>
                            </a>
                        </li>      
                        
                        <li class="nav-item active ml-2">
                            <a class="nav-link waves-effect waves-light active" href="#" >
                                <i class="fas fa-cog"></i>
                            </a>
                        </li>      
            
                        {% if avatar %}
                            <li class="nav-item dropdown avatar active ml-2">
                                <a class="nav-link dropdown-toggle p-0 pointer" id="sidebarCollapse">
                                    {{picture}}
                                    <img src="{{ url_for('main.getImage',image='{}.jpg'.format(current_user.id)) }}" class="rounded-circle z-depth-0" alt="avatar" height="35">
                                </a>
                            </li>      
                        {% else %}
                            <li class="nav-item dropdown active ml-2">
                                <a class="nav-link dropdown-toggle pointer" id="navbarDropdownMenuLink-333" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-user"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
                                    <a class="dropdown-item" href="#">Helizonaldo</a>
                                    <a class="dropdown-item" href="{{ url_for('auth.logout')}}">Logout</a>
                                </div>
                            </li>
                        {% endif %}
                    </ul>
                  
                </div>
            </nav>
            


        </div>


        <div class="overlay"></div>	



<!--        


<div class="form-group row">
  <label for="example-datetime-local-input" class="col-2 col-form-label">Date and time</label>
  <div class="col-10">
    <input class="form-control" type="datetime-local" value="2011-08-19T13:45:00" id="example-datetime-local-input">
  </div>
</div>


    <ul>
        <li class="xs">1 column xs</li>
        <li class="sm">2 column sm</li>
        <li class="md">3 column md</li>
        <li class="lg">4 column lg</li>
        <li class="xl">5 column xl</li>
    </ul>
-->


  
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New note</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ url_for('main.addTodo') }}" method="POST">
                <div class="modal-body">
                    {{ form.csrf_token }}
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Date Time:</label>
                        <div class='input-group date' id='datetimepicker1'>
                            {{ form.date_at(class="form-control") }}
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                            {% for error in form.date_at.errors %}
                                <span style="color:red">{{ error}}</span>
                            {% endfor %}
                        </div>
                    </div>              
                    <div class="form-group">
                        <label for="title" class="col-form-label">Title:</label>
                        <input type="text" class="form-control" id="title" name="title">
                    </div>
                    <div class="form-group">
                        <label for="description" class="col-form-label">Message:</label>
                        <textarea class="form-control" name="description" id="description"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type=submit id="submit" name="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>




<div class="row px-md-5 row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5" style="padding-top: 60px;">
    {% from 'components/todos.html' import todos_list %}
    {{ todos_list(todos) }}
</div>


</div>
{% endblock content %}

{% block script %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/lib/bootstrap-datetimepicker.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/lib/toastr.min.js') }}"></script>
    <script src="{{ url_for('main.static', filename='js/script.js') }}"></script>
    <script>
        //https://codeseven.github.io/toastr/
        
        
        $(function () {
            $('#datetimepicker1').datetimepicker();
        });
                
    </script>
{% endblock %}